update files for 1.8.0

diff --git a/bin/createScreenshots b/bin/createScreenshots
--- a/bin/createScreenshots
+++ b/bin/createScreenshots
@@ -11,17 +11,15 @@ function waitForEmulator {
     fail_counter=0
     timeout_in_sec=360
 
-    until [[ "$boot_animation" =~ "stopped" ]]; do
-      boot_animation=$(adb -s "$1" -e shell getprop init.svc.boot_animation 2>&1 &)
-      if [[ "$boot_animation" =~ "device not found" || "$boot_animation" =~ "device offline"
-        || "$boot_animation" =~ "running" ]]; then
-        (( fail_counter += 1 )) || true
-        echo "Waiting for emulator to start"
-        if [[ $fail_counter -gt timeout_in_sec ]]; then
-          echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
-          exit 1
-        fi
-      fi
+    until [[ "$boot_animation" == "1" ]]; do
+      boot_animation=$(adb -s "$1" -e shell getprop sys.boot_completed 2>&1 &)
+#      if [[ "$boot_animation" != "1" ]]; then
+#        echo "Waiting for emulator to start"
+#        if [[ $fail_counter -gt timeout_in_sec ]]; then
+#          echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
+#          exit 1
+#        fi
+#      fi
       sleep 1
     done
 
